annotations:
  catalog.cattle.io/certified: partner
  catalog.cattle.io/display-name: Elasticsearch
  catalog.cattle.io/kube-version: '>=1.14-0'
  catalog.cattle.io/release-name: elasticsearch
apiVersion: v1
appVersion: 7.17.3
description: Official Elastic helm chart for Elasticsearch
home: https://github.com/elastic/helm-charts
icon: https://helm.elastic.co/icons/elasticsearch.png
maintainers:
- email: helm-charts@elastic.co
  name: Elastic
name: elasticsearch
sources:
- https://github.com/elastic/elasticsearch
version: 7.17.3
