annotations:
  artifacthub.io/changes: |
    - "[Fixed]: Don't install CRDs for disabled components"
  catalog.cattle.io/certified: partner
  catalog.cattle.io/display-name: Argo CD
  catalog.cattle.io/kube-version: '>=1.22.0-0'
  catalog.cattle.io/release-name: argo-cd
apiVersion: v2
appVersion: v2.5.0
dependencies:
- condition: redis-ha.enabled
  name: redis-ha
  repository: file://./charts/redis-ha
  version: 4.22.2
description: A Helm chart for Argo CD, a declarative, GitOps continuous delivery tool
  for Kubernetes.
home: https://github.com/argoproj/argo-helm
icon: https://argo-cd.readthedocs.io/en/stable/assets/logo.png
keywords:
- argoproj
- argocd
- gitops
kubeVersion: '>=1.22.0-0'
maintainers:
- name: argoproj
  url: https://argoproj.github.io/
name: argo-cd
sources:
- https://github.com/argoproj/argo-helm/tree/main/charts/argo-cd
- https://github.com/argoproj/argo-cd
version: 5.12.1
