annotations:
  catalog.cattle.io/certified: partner
  catalog.cattle.io/display-name: Kibana
  catalog.cattle.io/kube-version: '>=1.14-0'
  catalog.cattle.io/release-name: kibana
apiVersion: v1
appVersion: 7.17.3
description: Official Elastic helm chart for Kibana
home: https://github.com/elastic/helm-charts
icon: https://helm.elastic.co/icons/kibana.png
maintainers:
- email: helm-charts@elastic.co
  name: Elastic
name: kibana
sources:
- https://github.com/elastic/kibana
version: 7.17.3
