annotations:
  catalog.cattle.io/certified: partner
  catalog.cattle.io/display-name: Logstash
  catalog.cattle.io/kube-version: '>=1.14-0'
  catalog.cattle.io/release-name: logstash
apiVersion: v1
appVersion: 7.17.3
description: Official Elastic helm chart for Logstash
home: https://github.com/elastic/helm-charts
icon: https://helm.elastic.co/icons/logstash.png
maintainers:
- email: helm-charts@elastic.co
  name: Elastic
name: logstash
sources:
- https://github.com/elastic/logstash
version: 7.17.3
